name: Deploy DNS Records

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: jungaretti/bacon-deploy-action@v2
        name: Deploy jungaretti.com
        with:
          api-key: ${{ secrets.PORKBUN_API_KEY }}
          secret-key: ${{ secrets.PORKBUN_SECRET_KEY }}
          config: dns/jungaretti.com.yml
          mode: force
      - uses: jungaretti/bacon-deploy-action@v2
        name: Deploy jamesungaretti.com
        with:
          api-key: ${{ secrets.PORKBUN_API_KEY }}
          secret-key: ${{ secrets.PORKBUN_SECRET_KEY }}
          config: dns/jamesungaretti.com.yml
          mode: force
